#Game Progress Data
#Wed Jun 18 14:26:35 CEST 2025
level_1_stars=3
level_1_unlocked=true
level_2_stars=3
level_2_unlocked=true
level_3_stars=3
level_3_unlocked=true
level_4_stars=3
level_4_unlocked=true
level_5_stars=3
level_5_unlocked=true
level_6_stars=3
level_6_unlocked=true
level_7_stars=3
level_7_unlocked=true
level_8_stars=3
level_8_unlocked=true
level_9_stars=0
level_9_unlocked=true
